backend:
  name: github
  repo: alberto56/presentation_gerrit_phabricator
  branch: gh-pages
  base_url: https://suresh-issue-82.dcycleproject.org
  auth_endpoint: /auth/github/repo/6920b81c09f96ec75f9b6ded
media_folder: static/uploads
public_folder: /uploads
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: '{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
